config/routes.rb
Rails.application.routes.draw do
 
  resources :picks
 
  resources :scores

  resources :drafts

  resources :users

  match ':controller(/:action(/:id))(.:format)', :via => [:get]
  root 'welcome#index'
  match "signup", :to => "users#new" , :via => [:get]
  match "login", :to => "sessions#login", :via => [:get]
  match "logout", :to => "sessions#logout", :via => [:get]
  match "login_attempt", :to => "sessions#login_attempt", :via => [:post]
  match "home", :to => "sessions#home", :via => [:get]
  match "profile", :to => "sessions#profile", :via => [:get]
  match "setting", :to => "sessions#setting", :via => [:get]
  match "admin", :to => "drafts#admin" , :via => [:get]

end

app/models/bachelorette.rb
class Bachelorette < ActiveRecord::Base
end

app/models/draft.rb
class Draft < ActiveRecord::Base
end

app/models/pick.rb
class Pick < ActiveRecord::Base
end

app/models/score.rb
class Score < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password

  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true
  #Only on Create so other actions like update password attribute can be nil
  validates_length_of :password, :in => 6..20, :on => :create

  def self.authenticate(username_or_email="", login_password="")

    if  EMAIL_REGEX.match(username_or_email)    
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end   

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end



  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
  def authenticate_user
  	unless session[:user_id]
  		redirect_to(:controller => 'sessions', :action => 'login')
  		return false
  	else
      # set current_user by the current user object
      @current_user = User.find session[:user_id] 
  		return true
  	end
  end

  #This method for prevent user to access Signup & Login Page without logout
  def save_login_state
    if session[:user_id]
            redirect_to(:controller => 'sessions', :action => 'home')
      return false
    else
      return true
    end
  end
end

app/controllers/bachelorettes_controller.rb
class BachelorettesController < ApplicationController
  def index
    @bachelorettes = Bachelorette.all
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
   before_filter :authenticate_user, :except => [:index, :login, :login_attempt, :logout]

  def index
    @drafts = Draft.all
  end

  def show
    @draft = Draft.find(params[:id])
  end

  def new
  end

  def create
    @draft = Draft.new(params.require(:draft).permit(:player, :round, :bachelor)) 
    @draft.save
    redirect_to @draft  
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController

  before_filter :authenticate_user, :except => [:index, :login, :login_attempt, :logout]

  def index
    @picks = Pick.all
  end

  def show
    @pick = Pick.find(params[:id])
  end

  def new
  end

  def create
    @pick = Pick.new(params.require(:pick).permit(:player, :week, :rose, :tears, :bachelorette)) 
    @pick.save
    redirect_to @pick  
  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.order("total DESC")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
	before_filter :authenticate_user, :except => [:index, :login, :login_attempt, :logout]
	before_filter :save_login_state, :only => [:index, :login, :login_attempt]

	def home
		#Home Page
	end

	def profile
		#Profile Page
	end

	def setting
		#Setting Page
	end

	def login
		#Login Form
	end

	def login_attempt
		authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
		if authorized_user
			session[:user_id] = authorized_user.id
			flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.username}"
			redirect_to(:action => 'home')


		else
			flash[:notice] = "Invalid Username or Password"
        	flash[:color]= "invalid"
			render "login"	
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to :action => 'login'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id])
  end

  def new
    @user = User.new 
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
      redirect_to :action => :index
    else
      render "new"
    end
  end
  def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bachelorettes_helper.rb
module BachelorettesHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bachelorettes/index.html.erb
<h1>Listing Bachelorettes</h1>
 
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>   
  </tr>
 
  <% @bachelorettes.each do |bachelorette| %>
    <tr>
      <td><%= bachelorette.id %></td>
      <td><%= bachelorette.name %></td>
    </tr>
  <% end %>
</table>

app/views/drafts/admin.html.erb
<h2 class='User_Header'>Admin Draft Pick <h2>


<%= form_for :draft, url: drafts_path do |f| %>

  <p> Username:</br> <%= f.text_field :player%> </p>


  <p>
    <%= f.label "Round" %><br>
    <%= f.select :round, [['1', '1'],['2','2'],['3','3'],['4','4'],['Winner Pick','5']] %>
  </p>  

  <p>
    <%= f.label "Bachelor" %><br>
    <%= f.select :bachelor, [['Rachel'],['Vanessa'],['Danielle L.'],['Christen'],['Astrid'],['Corinne'],['Elizabeth'],['Jasmine G.'],['Raven'],['Kristina'],['Danielle M.'],['Sarah'],['Josephine'],['Lacey'],['Taylor'],['Alexis'],['Hailey'],['Whitney'],['Dominique'],['Jaimi'],['Brittany'],['Liz']] %>
  </p>
 
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/drafts/index.html.erb
<h1>Draft Picks</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Round</th>
    <th>Bachelor</th>
  </tr>
 
  <% @drafts.each do |draft| %>
    <tr>
      <td><%= draft.player %></td>
      <td><%= draft.round %></td>
      <td><%= draft.bachelor %></td>
    </tr>
  <% end %>
</table>

app/views/drafts/new.html.erb
<h2 class='User_Header'>New <%=@current_user.username%> Draft Pick <h2>


<%= form_for :draft, url: drafts_path do |f| %>

  <%= f.hidden_field :player, :value => @current_user.username %> 


  <p>
    <%= f.label "Round" %><br>
    <%= f.select :round, [['1', '1'],['2','2'],['3','3'],['4','4'],['Winner Pick','5']] %>
  </p>  

  <p>
    <%= f.label "Bachelor" %><br>
    <%= f.select :bachelor, [['Rachel'],['Vanessa'],['Danielle L.'],['Christen'],['Astrid'],['Corinne'],['Elizabeth'],['Jasmine G.'],['Raven'],['Kristina'],['Danielle M.'],['Sarah'],['Josephine'],['Lacey'],['Taylor'],['Alexis'],['Hailey'],['Whitney'],['Dominique'],['Jaimi'],['Brittany'],['Liz']] %>
  </p>
 
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/drafts/show.html.erb
<p>
  <strong>Player:</strong>
  <%= @draft.player %>
</p>
 
<p>
  <strong>round:</strong>
  <%= @draft.round %>
</p>

<p>
  <strong>Bachelor:</strong>
  <%= @draft.bachelor %>
</p>

app/views/picks/index.html.erb
<h1>Picks</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Week</th>
    <th>Rose</th>
    <th>Tears</th> 
    <th>Bachelorette</th>    
  </tr>
 
  <% @picks.each do |pick| %>
    <tr>
      <td><%= pick.player %></td>
      <td><%= pick.week %></td>
      <td><%= pick.rose %></td>
      <td><%= pick.tears %></td>
      <td><%= pick.bachelorette %></td>
    </tr>
  <% end %>
</table>

app/views/picks/new.html.erb
<h2 class='User_Header'>New <%=@current_user.username%> Pick <h2>

<%= form_for :pick, url: picks_path do |f| %>
  
  <%= f.hidden_field :player, :value => @current_user.username %> 

  <%= f.hidden_field :week, :value => '11' %> 


  <p>
    <%= f.label "Rose" %><br>
    <%= f.select :rose, [['Vanessa'],['Raven'],['Nick picks neither woman']]  %>
  </p>

  <p>
    <%= f.label "Tears" %><br>
    <%= f.select :tears, [['Vanessa'],['Raven']] %>
  </p>
<!-- 
  <p>
    <%= f.label "Next Bachelor" %><br>
    <%= f.select :bachelorette, [['Jordan'],['Luke'],['Wells'],['James T.'],['Grant'],['Derek'],['Christian'],['Chad'],['Chase'],['Alex'],['Robby'],['Brandon'],['James F.'],['Ali'],['Nick B.'],['Will'],['James S.'],['Vinny'],['Evan'],['Daniel']]  %>
  </p> -->

  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/picks/show.html.erb
<h2 class='User_Header'>New <%=@current_user.username%> view picks <h2>

<p>
  <strong>Player:</strong>
  <%= @pick.player %>
</p>
 
<p>
  <strong>Week:</strong>
  <%= @pick.week %>
</p>

<p>
  <strong>Rose:</strong>
  <%= @pick.rose %>
</p>

<p>
  <strong>Tears:</strong>
  <%= @pick.tears %>
</p>

<!-- <p>
  <strong>Bachelorette:</strong>
  <%= @pick.bachelorette %>
</p> -->

app/views/scores/index.html.erb
<h1>Scores</h1>
 
<table class="table">
  <tr>
    <th>Name</th>
    <th>Total</th>
    <th>Week2</th>   
    <th>Week3</th>   
    <th>Week4</th>   
    <th>Week5</th>   
    <th>Week6</th>   
    <th>Week7</th>   
    <th>Week8</th>   
    <th>Week9</th>   
    <th>Week10</th> 
    <th>Week11</th> 
    <th>Winner Pick</th>     
<!--     <th>New Bachelorette Pick</th>     
 -->  </tr>
 
  <% @scores.each do |score| %>
    <tr>
      <td><%= score.player_name %></td>
      <td><%= score.total %></td>
      <td><%= score.week_2 %></td>
      <td><%= score.week_3 %></td>
      <td><%= score.week_4 %></td>
      <td><%= score.week_5 %></td>
      <td><%= score.week_6 %></td>
      <td><%= score.week_7 %></td>
      <td><%= score.week_8 %></td>
      <td><%= score.week_9 %></td>
      <td><%= score.week_10 %></td>
      <td><%= score.week_11 %></td>
      <td><%= score.correct_final_pick %></td>
<!--       <td><%= score.bachelorette_pick %></td>
 -->
    </tr>
  <% end %>
</table>

app/views/users/index.html.erb
<h3>Signups</h3>
 
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>   
    <th>Paid?</th>   
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.paid %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h3>Sign Up</h3>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<h3>Thanks for signing up!</h3>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>

app/views/welcome/index.html.erb
<div id = "main" align = "center">
<h1 align = "center">Sign up for the new season <%= link_to 'here', new_user_path %></h1>
<%= image_tag "nick_cast.jpg" %>
</div>

<h1 align = "center">Draft Begins Sunday 1/8 at 8pm EST</h1>